### ISSUE TITLE
822 Error 143

### ISSUE THREAD

**Issue by billlange1968** [FujiNetWIFI/atariwifi#233]
When I connect my 822 directly to my 130XE and do a LPRINT from basic, it works. When using FUJINET passthrough, I get an error: Error-143 Serial bus data frame checksum error.

**Comment by tschak909** [comment]
Problem is caused by printer device on #FujiNet conflicting with the physically connected printer.

Solution is to create mechanism to re-assign or disable printer device, that can be called over SIO or used via web admin. 

@jeffpiep and @kaelef need to collaborate on a mechanism to make this happen.

**Comment by kaelef** [comment]
Latest commit provides a simple mechanism for changing FujiNet's printer emulation port.
